###
GET https://api-inventariolibros-ricaldone.herokuapp.com/api HTTP/1.1

###
POST https://api-inventariolibros-ricaldone.herokuapp.com/api HTTP/1.1
Content-Type: application/json

{
    "titulo": "libro 4",
    "autor": "autor libro 4",
    "edicion": 8
}

###
DELETE https://api-inventariolibros-ricaldone.herokuapp.com/api/3 HTTP/1.1

###
PUT https://api-inventariolibros-ricaldone.herokuapp.com/4 HTTP/1.1
Content-Type: application/json

{
    "titulo": "libro cuarto",
    "autor": "autor libro 3",
    "edicion": 6
}